
controllers:
    name_prefix: workingforum_
    resource: ../../Controller/
    type: annotation


workingforum_forum:
    path: /{forumSlug}
    controller: Yosimitso\WorkingForumBundle\Controller\ForumController::forumAction

workingforum_subforum:
    path: /{forumSlug}/{subforumSlug}
    controller: Yosimitso\WorkingForumBundle\Controller\ForumController::subforumAction

workingforum_new_thread:
    path: /{forumSlug}/{subforumSlug}/new-thread
    controller: Yosimitso\WorkingForumBundle\Controller\ThreadController::newAction

workingforum_thread:
    path: /{forumSlug}/{subforumSlug}/{threadId}-{threadSlug}
    requirements:
        threadId: \d+
    controller: Yosimitso\WorkingForumBundle\Controller\ThreadController::indexAction
